### ISSUE TITLE
8 axis joystick

### ISSUE THREAD

**Issue by davieli2** [Rabbid76/python_windows_joystickapi#1]
Hi,
I connect a joystick board (Leo Bodnar BU0836A) with 8 axis but with joystickapi  I'm able to see only six of them (obviously Windows see all eight axis)

**Comment by davieli2** [comment]
where all data from joystick pass inside joystickapi.py ?

**Comment by Rabbid76** [comment]
There are no data "passed in". This is just a python wrapper for (WINMM.dll). See [joyGetDevCapsW](https://docs.microsoft.com/en-us/windows/win32/api/joystickapi/nf-joystickapi-joygetdevcapsw). Note, this is not a library or toolbox, it is just an example which I've created as an answer for a StackOverflow question: [How to get USB controller/gamepad to work with python](https://stackoverflow.com/questions/60309652/how-to-get-usb-controller-gamepad-to-work-with-python).

**Comment by davieli2** [comment]
do you have an idea where the two axis missing can be catch ?

**Comment by Rabbid76** [comment]
No. As far as I know the [Windows Multimedia](https://docs.microsoft.com/en-us/windows/win32/api/_multimedia/) only supports 6 axis. The data structur [`JOYCAPS`](https://docs.microsoft.com/de-de/previous-versions/dd757103(v=vs.85)) cannot handle mor than 6 axis.
